# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _calculix_pythoninterface
else:
    import _calculix_pythoninterface

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _calculix_pythoninterface.delete_SwigPyIterator

    def value(self) -> "PyObject *":
        return _calculix_pythoninterface.SwigPyIterator_value(self)

    def incr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.SwigPyIterator_incr(self, n)

    def decr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.SwigPyIterator_decr(self, n)

    def distance(self, x: "SwigPyIterator") -> "ptrdiff_t":
        return _calculix_pythoninterface.SwigPyIterator_distance(self, x)

    def equal(self, x: "SwigPyIterator") -> "bool":
        return _calculix_pythoninterface.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _calculix_pythoninterface.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _calculix_pythoninterface.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _calculix_pythoninterface.SwigPyIterator_previous(self)

    def advance(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.SwigPyIterator_advance(self, n)

    def __eq__(self, x: "SwigPyIterator") -> "bool":
        return _calculix_pythoninterface.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: "SwigPyIterator") -> "bool":
        return _calculix_pythoninterface.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _calculix_pythoninterface.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _calculix_pythoninterface.SwigPyIterator___isub__(self, n)

    def __add__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _calculix_pythoninterface.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _calculix_pythoninterface:
_calculix_pythoninterface.SwigPyIterator_swigregister(SwigPyIterator)

class vectori(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _calculix_pythoninterface.vectori___nonzero__(self)

    def __bool__(self) -> "bool":
        return _calculix_pythoninterface.vectori___bool__(self)

    def __len__(self) -> "std::vector< int >::size_type":
        return _calculix_pythoninterface.vectori___len__(self)

    def __getslice__(self, i: "std::vector< int >::difference_type", j: "std::vector< int >::difference_type") -> "std::vector< int,std::allocator< int > > *":
        return _calculix_pythoninterface.vectori___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _calculix_pythoninterface.vectori___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< int >::difference_type", j: "std::vector< int >::difference_type") -> "void":
        return _calculix_pythoninterface.vectori___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectori___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< int >::value_type const &":
        return _calculix_pythoninterface.vectori___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectori___setitem__(self, *args)

    def pop(self) -> "std::vector< int >::value_type":
        return _calculix_pythoninterface.vectori_pop(self)

    def append(self, x: "std::vector< int >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectori_append(self, x)

    def empty(self) -> "bool":
        return _calculix_pythoninterface.vectori_empty(self)

    def size(self) -> "std::vector< int >::size_type":
        return _calculix_pythoninterface.vectori_size(self)

    def swap(self, v: "vectori") -> "void":
        return _calculix_pythoninterface.vectori_swap(self, v)

    def begin(self) -> "std::vector< int >::iterator":
        return _calculix_pythoninterface.vectori_begin(self)

    def end(self) -> "std::vector< int >::iterator":
        return _calculix_pythoninterface.vectori_end(self)

    def rbegin(self) -> "std::vector< int >::reverse_iterator":
        return _calculix_pythoninterface.vectori_rbegin(self)

    def rend(self) -> "std::vector< int >::reverse_iterator":
        return _calculix_pythoninterface.vectori_rend(self)

    def clear(self) -> "void":
        return _calculix_pythoninterface.vectori_clear(self)

    def get_allocator(self) -> "std::vector< int >::allocator_type":
        return _calculix_pythoninterface.vectori_get_allocator(self)

    def pop_back(self) -> "void":
        return _calculix_pythoninterface.vectori_pop_back(self)

    def erase(self, *args) -> "std::vector< int >::iterator":
        return _calculix_pythoninterface.vectori_erase(self, *args)

    def __init__(self, *args):
        _calculix_pythoninterface.vectori_swiginit(self, _calculix_pythoninterface.new_vectori(*args))

    def push_back(self, x: "std::vector< int >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectori_push_back(self, x)

    def front(self) -> "std::vector< int >::value_type const &":
        return _calculix_pythoninterface.vectori_front(self)

    def back(self) -> "std::vector< int >::value_type const &":
        return _calculix_pythoninterface.vectori_back(self)

    def assign(self, n: "std::vector< int >::size_type", x: "std::vector< int >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectori_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _calculix_pythoninterface.vectori_resize(self, *args)

    def insert(self, *args) -> "void":
        return _calculix_pythoninterface.vectori_insert(self, *args)

    def reserve(self, n: "std::vector< int >::size_type") -> "void":
        return _calculix_pythoninterface.vectori_reserve(self, n)

    def capacity(self) -> "std::vector< int >::size_type":
        return _calculix_pythoninterface.vectori_capacity(self)
    __swig_destroy__ = _calculix_pythoninterface.delete_vectori

# Register vectori in _calculix_pythoninterface:
_calculix_pythoninterface.vectori_swigregister(vectori)

class vectorf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.vectorf_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _calculix_pythoninterface.vectorf___nonzero__(self)

    def __bool__(self) -> "bool":
        return _calculix_pythoninterface.vectorf___bool__(self)

    def __len__(self) -> "std::vector< float >::size_type":
        return _calculix_pythoninterface.vectorf___len__(self)

    def __getslice__(self, i: "std::vector< float >::difference_type", j: "std::vector< float >::difference_type") -> "std::vector< float,std::allocator< float > > *":
        return _calculix_pythoninterface.vectorf___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _calculix_pythoninterface.vectorf___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< float >::difference_type", j: "std::vector< float >::difference_type") -> "void":
        return _calculix_pythoninterface.vectorf___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectorf___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< float >::value_type const &":
        return _calculix_pythoninterface.vectorf___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectorf___setitem__(self, *args)

    def pop(self) -> "std::vector< float >::value_type":
        return _calculix_pythoninterface.vectorf_pop(self)

    def append(self, x: "std::vector< float >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectorf_append(self, x)

    def empty(self) -> "bool":
        return _calculix_pythoninterface.vectorf_empty(self)

    def size(self) -> "std::vector< float >::size_type":
        return _calculix_pythoninterface.vectorf_size(self)

    def swap(self, v: "vectorf") -> "void":
        return _calculix_pythoninterface.vectorf_swap(self, v)

    def begin(self) -> "std::vector< float >::iterator":
        return _calculix_pythoninterface.vectorf_begin(self)

    def end(self) -> "std::vector< float >::iterator":
        return _calculix_pythoninterface.vectorf_end(self)

    def rbegin(self) -> "std::vector< float >::reverse_iterator":
        return _calculix_pythoninterface.vectorf_rbegin(self)

    def rend(self) -> "std::vector< float >::reverse_iterator":
        return _calculix_pythoninterface.vectorf_rend(self)

    def clear(self) -> "void":
        return _calculix_pythoninterface.vectorf_clear(self)

    def get_allocator(self) -> "std::vector< float >::allocator_type":
        return _calculix_pythoninterface.vectorf_get_allocator(self)

    def pop_back(self) -> "void":
        return _calculix_pythoninterface.vectorf_pop_back(self)

    def erase(self, *args) -> "std::vector< float >::iterator":
        return _calculix_pythoninterface.vectorf_erase(self, *args)

    def __init__(self, *args):
        _calculix_pythoninterface.vectorf_swiginit(self, _calculix_pythoninterface.new_vectorf(*args))

    def push_back(self, x: "std::vector< float >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectorf_push_back(self, x)

    def front(self) -> "std::vector< float >::value_type const &":
        return _calculix_pythoninterface.vectorf_front(self)

    def back(self) -> "std::vector< float >::value_type const &":
        return _calculix_pythoninterface.vectorf_back(self)

    def assign(self, n: "std::vector< float >::size_type", x: "std::vector< float >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectorf_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _calculix_pythoninterface.vectorf_resize(self, *args)

    def insert(self, *args) -> "void":
        return _calculix_pythoninterface.vectorf_insert(self, *args)

    def reserve(self, n: "std::vector< float >::size_type") -> "void":
        return _calculix_pythoninterface.vectorf_reserve(self, n)

    def capacity(self) -> "std::vector< float >::size_type":
        return _calculix_pythoninterface.vectorf_capacity(self)
    __swig_destroy__ = _calculix_pythoninterface.delete_vectorf

# Register vectorf in _calculix_pythoninterface:
_calculix_pythoninterface.vectorf_swigregister(vectorf)

class vectord(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _calculix_pythoninterface.vectord___nonzero__(self)

    def __bool__(self) -> "bool":
        return _calculix_pythoninterface.vectord___bool__(self)

    def __len__(self) -> "std::vector< double >::size_type":
        return _calculix_pythoninterface.vectord___len__(self)

    def __getslice__(self, i: "std::vector< double >::difference_type", j: "std::vector< double >::difference_type") -> "std::vector< double,std::allocator< double > > *":
        return _calculix_pythoninterface.vectord___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _calculix_pythoninterface.vectord___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< double >::difference_type", j: "std::vector< double >::difference_type") -> "void":
        return _calculix_pythoninterface.vectord___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectord___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< double >::value_type const &":
        return _calculix_pythoninterface.vectord___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectord___setitem__(self, *args)

    def pop(self) -> "std::vector< double >::value_type":
        return _calculix_pythoninterface.vectord_pop(self)

    def append(self, x: "std::vector< double >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectord_append(self, x)

    def empty(self) -> "bool":
        return _calculix_pythoninterface.vectord_empty(self)

    def size(self) -> "std::vector< double >::size_type":
        return _calculix_pythoninterface.vectord_size(self)

    def swap(self, v: "vectord") -> "void":
        return _calculix_pythoninterface.vectord_swap(self, v)

    def begin(self) -> "std::vector< double >::iterator":
        return _calculix_pythoninterface.vectord_begin(self)

    def end(self) -> "std::vector< double >::iterator":
        return _calculix_pythoninterface.vectord_end(self)

    def rbegin(self) -> "std::vector< double >::reverse_iterator":
        return _calculix_pythoninterface.vectord_rbegin(self)

    def rend(self) -> "std::vector< double >::reverse_iterator":
        return _calculix_pythoninterface.vectord_rend(self)

    def clear(self) -> "void":
        return _calculix_pythoninterface.vectord_clear(self)

    def get_allocator(self) -> "std::vector< double >::allocator_type":
        return _calculix_pythoninterface.vectord_get_allocator(self)

    def pop_back(self) -> "void":
        return _calculix_pythoninterface.vectord_pop_back(self)

    def erase(self, *args) -> "std::vector< double >::iterator":
        return _calculix_pythoninterface.vectord_erase(self, *args)

    def __init__(self, *args):
        _calculix_pythoninterface.vectord_swiginit(self, _calculix_pythoninterface.new_vectord(*args))

    def push_back(self, x: "std::vector< double >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectord_push_back(self, x)

    def front(self) -> "std::vector< double >::value_type const &":
        return _calculix_pythoninterface.vectord_front(self)

    def back(self) -> "std::vector< double >::value_type const &":
        return _calculix_pythoninterface.vectord_back(self)

    def assign(self, n: "std::vector< double >::size_type", x: "std::vector< double >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectord_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _calculix_pythoninterface.vectord_resize(self, *args)

    def insert(self, *args) -> "void":
        return _calculix_pythoninterface.vectord_insert(self, *args)

    def reserve(self, n: "std::vector< double >::size_type") -> "void":
        return _calculix_pythoninterface.vectord_reserve(self, n)

    def capacity(self) -> "std::vector< double >::size_type":
        return _calculix_pythoninterface.vectord_capacity(self)
    __swig_destroy__ = _calculix_pythoninterface.delete_vectord

# Register vectord in _calculix_pythoninterface:
_calculix_pythoninterface.vectord_swigregister(vectord)

class vectors(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.vectors_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _calculix_pythoninterface.vectors___nonzero__(self)

    def __bool__(self) -> "bool":
        return _calculix_pythoninterface.vectors___bool__(self)

    def __len__(self) -> "std::vector< std::string >::size_type":
        return _calculix_pythoninterface.vectors___len__(self)

    def __getslice__(self, i: "std::vector< std::string >::difference_type", j: "std::vector< std::string >::difference_type") -> "std::vector< std::string,std::allocator< std::string > > *":
        return _calculix_pythoninterface.vectors___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _calculix_pythoninterface.vectors___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< std::string >::difference_type", j: "std::vector< std::string >::difference_type") -> "void":
        return _calculix_pythoninterface.vectors___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectors___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::string >::value_type const &":
        return _calculix_pythoninterface.vectors___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _calculix_pythoninterface.vectors___setitem__(self, *args)

    def pop(self) -> "std::vector< std::string >::value_type":
        return _calculix_pythoninterface.vectors_pop(self)

    def append(self, x: "std::vector< std::string >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectors_append(self, x)

    def empty(self) -> "bool":
        return _calculix_pythoninterface.vectors_empty(self)

    def size(self) -> "std::vector< std::string >::size_type":
        return _calculix_pythoninterface.vectors_size(self)

    def swap(self, v: "vectors") -> "void":
        return _calculix_pythoninterface.vectors_swap(self, v)

    def begin(self) -> "std::vector< std::string >::iterator":
        return _calculix_pythoninterface.vectors_begin(self)

    def end(self) -> "std::vector< std::string >::iterator":
        return _calculix_pythoninterface.vectors_end(self)

    def rbegin(self) -> "std::vector< std::string >::reverse_iterator":
        return _calculix_pythoninterface.vectors_rbegin(self)

    def rend(self) -> "std::vector< std::string >::reverse_iterator":
        return _calculix_pythoninterface.vectors_rend(self)

    def clear(self) -> "void":
        return _calculix_pythoninterface.vectors_clear(self)

    def get_allocator(self) -> "std::vector< std::string >::allocator_type":
        return _calculix_pythoninterface.vectors_get_allocator(self)

    def pop_back(self) -> "void":
        return _calculix_pythoninterface.vectors_pop_back(self)

    def erase(self, *args) -> "std::vector< std::string >::iterator":
        return _calculix_pythoninterface.vectors_erase(self, *args)

    def __init__(self, *args):
        _calculix_pythoninterface.vectors_swiginit(self, _calculix_pythoninterface.new_vectors(*args))

    def push_back(self, x: "std::vector< std::string >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectors_push_back(self, x)

    def front(self) -> "std::vector< std::string >::value_type const &":
        return _calculix_pythoninterface.vectors_front(self)

    def back(self) -> "std::vector< std::string >::value_type const &":
        return _calculix_pythoninterface.vectors_back(self)

    def assign(self, n: "std::vector< std::string >::size_type", x: "std::vector< std::string >::value_type const &") -> "void":
        return _calculix_pythoninterface.vectors_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _calculix_pythoninterface.vectors_resize(self, *args)

    def insert(self, *args) -> "void":
        return _calculix_pythoninterface.vectors_insert(self, *args)

    def reserve(self, n: "std::vector< std::string >::size_type") -> "void":
        return _calculix_pythoninterface.vectors_reserve(self, n)

    def capacity(self) -> "std::vector< std::string >::size_type":
        return _calculix_pythoninterface.vectors_capacity(self)
    __swig_destroy__ = _calculix_pythoninterface.delete_vectors

# Register vectors in _calculix_pythoninterface:
_calculix_pythoninterface.vectors_swigregister(vectors)

class pairi_i(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _calculix_pythoninterface.pairi_i_swiginit(self, _calculix_pythoninterface.new_pairi_i(*args))
    first = property(_calculix_pythoninterface.pairi_i_first_get, _calculix_pythoninterface.pairi_i_first_set)
    second = property(_calculix_pythoninterface.pairi_i_second_get, _calculix_pythoninterface.pairi_i_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _calculix_pythoninterface.delete_pairi_i

# Register pairi_i in _calculix_pythoninterface:
_calculix_pythoninterface.pairi_i_swigregister(pairi_i)

class VectorPairi(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _calculix_pythoninterface.VectorPairi_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _calculix_pythoninterface.VectorPairi___nonzero__(self)

    def __bool__(self) -> "bool":
        return _calculix_pythoninterface.VectorPairi___bool__(self)

    def __len__(self) -> "std::vector< std::pair< int,int > >::size_type":
        return _calculix_pythoninterface.VectorPairi___len__(self)

    def __getslice__(self, i: "std::vector< std::pair< int,int > >::difference_type", j: "std::vector< std::pair< int,int > >::difference_type") -> "std::vector< std::pair< int,int >,std::allocator< std::pair< int,int > > > *":
        return _calculix_pythoninterface.VectorPairi___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _calculix_pythoninterface.VectorPairi___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< std::pair< int,int > >::difference_type", j: "std::vector< std::pair< int,int > >::difference_type") -> "void":
        return _calculix_pythoninterface.VectorPairi___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _calculix_pythoninterface.VectorPairi___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::pair< int,int > >::value_type const &":
        return _calculix_pythoninterface.VectorPairi___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _calculix_pythoninterface.VectorPairi___setitem__(self, *args)

    def pop(self) -> "std::vector< std::pair< int,int > >::value_type":
        return _calculix_pythoninterface.VectorPairi_pop(self)

    def append(self, x: "pairi_i") -> "void":
        return _calculix_pythoninterface.VectorPairi_append(self, x)

    def empty(self) -> "bool":
        return _calculix_pythoninterface.VectorPairi_empty(self)

    def size(self) -> "std::vector< std::pair< int,int > >::size_type":
        return _calculix_pythoninterface.VectorPairi_size(self)

    def swap(self, v: "VectorPairi") -> "void":
        return _calculix_pythoninterface.VectorPairi_swap(self, v)

    def begin(self) -> "std::vector< std::pair< int,int > >::iterator":
        return _calculix_pythoninterface.VectorPairi_begin(self)

    def end(self) -> "std::vector< std::pair< int,int > >::iterator":
        return _calculix_pythoninterface.VectorPairi_end(self)

    def rbegin(self) -> "std::vector< std::pair< int,int > >::reverse_iterator":
        return _calculix_pythoninterface.VectorPairi_rbegin(self)

    def rend(self) -> "std::vector< std::pair< int,int > >::reverse_iterator":
        return _calculix_pythoninterface.VectorPairi_rend(self)

    def clear(self) -> "void":
        return _calculix_pythoninterface.VectorPairi_clear(self)

    def get_allocator(self) -> "std::vector< std::pair< int,int > >::allocator_type":
        return _calculix_pythoninterface.VectorPairi_get_allocator(self)

    def pop_back(self) -> "void":
        return _calculix_pythoninterface.VectorPairi_pop_back(self)

    def erase(self, *args) -> "std::vector< std::pair< int,int > >::iterator":
        return _calculix_pythoninterface.VectorPairi_erase(self, *args)

    def __init__(self, *args):
        _calculix_pythoninterface.VectorPairi_swiginit(self, _calculix_pythoninterface.new_VectorPairi(*args))

    def push_back(self, x: "pairi_i") -> "void":
        return _calculix_pythoninterface.VectorPairi_push_back(self, x)

    def front(self) -> "std::vector< std::pair< int,int > >::value_type const &":
        return _calculix_pythoninterface.VectorPairi_front(self)

    def back(self) -> "std::vector< std::pair< int,int > >::value_type const &":
        return _calculix_pythoninterface.VectorPairi_back(self)

    def assign(self, n: "std::vector< std::pair< int,int > >::size_type", x: "pairi_i") -> "void":
        return _calculix_pythoninterface.VectorPairi_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _calculix_pythoninterface.VectorPairi_resize(self, *args)

    def insert(self, *args) -> "void":
        return _calculix_pythoninterface.VectorPairi_insert(self, *args)

    def reserve(self, n: "std::vector< std::pair< int,int > >::size_type") -> "void":
        return _calculix_pythoninterface.VectorPairi_reserve(self, n)

    def capacity(self) -> "std::vector< std::pair< int,int > >::size_type":
        return _calculix_pythoninterface.VectorPairi_capacity(self)
    __swig_destroy__ = _calculix_pythoninterface.delete_VectorPairi

# Register VectorPairi in _calculix_pythoninterface:
_calculix_pythoninterface.VectorPairi_swigregister(VectorPairi)

class CalculiXPythonInterface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _calculix_pythoninterface.CalculiXPythonInterface_swiginit(self, _calculix_pythoninterface.new_CalculiXPythonInterface())
    __swig_destroy__ = _calculix_pythoninterface.delete_CalculiXPythonInterface

    def help(self) -> "void":
        return _calculix_pythoninterface.CalculiXPythonInterface_help(self)

    def test_int(self) -> "int":
        return _calculix_pythoninterface.CalculiXPythonInterface_test_int(self)

    def test_double(self) -> "double":
        return _calculix_pythoninterface.CalculiXPythonInterface_test_double(self)

    def test_string(self) -> "std::string":
        return _calculix_pythoninterface.CalculiXPythonInterface_test_string(self)

    def to_string_scientific(self, value: "double", precision: "int"=6) -> "std::string":
        return _calculix_pythoninterface.CalculiXPythonInterface_to_string_scientific(self, value, precision)
    ccx_iface = property(_calculix_pythoninterface.CalculiXPythonInterface_ccx_iface_get, _calculix_pythoninterface.CalculiXPythonInterface_ccx_iface_set)

# Register CalculiXPythonInterface in _calculix_pythoninterface:
_calculix_pythoninterface.CalculiXPythonInterface_swigregister(CalculiXPythonInterface)



