# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _CalculiXCoreInterface
else:
    import _CalculiXCoreInterface

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class CalculiXCoreInterface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _CalculiXCoreInterface.CalculiXCoreInterface_swiginit(self, _CalculiXCoreInterface.new_CalculiXCoreInterface())
    __swig_destroy__ = _CalculiXCoreInterface.delete_CalculiXCoreInterface

    def set_use_ccx_autocleanup(self, bool_use):
        return _CalculiXCoreInterface.CalculiXCoreInterface_set_use_ccx_autocleanup(self, bool_use)

    def set_use_ccx_logfile(self, bool_use):
        return _CalculiXCoreInterface.CalculiXCoreInterface_set_use_ccx_logfile(self, bool_use)

    def print_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_print_data(self)

    def log_str(self, str_log):
        return _CalculiXCoreInterface.CalculiXCoreInterface_log_str(self, str_log)

    def parser(self, parse_type, parse_string):
        return _CalculiXCoreInterface.CalculiXCoreInterface_parser(self, parse_type, parse_string)

    def to_string_scientific(self, value, precision=6):
        return _CalculiXCoreInterface.CalculiXCoreInterface_to_string_scientific(self, value, precision)

    def string_scientific_to_double(self, value, precision=6):
        return _CalculiXCoreInterface.CalculiXCoreInterface_string_scientific_to_double(self, value, precision)

    def get_ccx_element_types(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_ccx_element_types(self)

    def set_ccx_element_type(self, block_id, ccx_element_type):
        return _CalculiXCoreInterface.CalculiXCoreInterface_set_ccx_element_type(self, block_id, ccx_element_type)

    def get_ccx_element_type(self, block_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_ccx_element_type(self, block_id)

    def get_cubit_element_type_entity(self, cubit_element_type):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_cubit_element_type_entity(self, cubit_element_type)

    def get_element_id_type_connectivity(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_element_id_type_connectivity(self)

    def get_block_name(self, block_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_block_name(self, block_id)

    def get_block_node_ids(self, block_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_block_node_ids(self, block_id)

    def get_block_element_ids(self, block_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_block_element_ids(self, block_id)

    def get_material_name(self, material_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_material_name(self, material_id)

    def get_nodeset_name(self, nodeset_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_nodeset_name(self, nodeset_id)

    def get_sideset_name(self, sideset_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_sideset_name(self, sideset_id)

    def get_surfaceinteraction_name(self, surfaceinteraction_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_surfaceinteraction_name(self, surfaceinteraction_id)

    def get_contactpair_master_slave(self, contactpair_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_contactpair_master_slave(self, contactpair_id)

    def get_amplitude_name(self, amplitude_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_amplitude_name(self, amplitude_id)

    def check_block_exists(self, block_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_check_block_exists(self, block_id)

    def check_nodeset_exists(self, nodeset_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_check_nodeset_exists(self, nodeset_id)

    def check_sideset_exists(self, sideset_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_check_sideset_exists(self, sideset_id)

    def check_vertex_in_nodeset_exists(self, vertex_id, nodeset_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_check_vertex_in_nodeset_exists(self, vertex_id, nodeset_id)

    def core_update(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_core_update(self)

    def core_reset(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_core_reset(self)

    def get_blocks(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_blocks(self)

    def get_ccx_element_side(self, element_type, side):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_ccx_element_side(self, element_type, side)

    def add_sideset_face(self, sideset_id, sideset_name, face, element_type):
        return _CalculiXCoreInterface.CalculiXCoreInterface_add_sideset_face(self, sideset_id, sideset_name, face, element_type)

    def get_sideset_face(self, sideset_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_sideset_face(self, sideset_id)

    def get_material_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_material_export_data(self)

    def get_section_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_section_export_data(self)

    def get_constraint_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_constraint_export_data(self)

    def get_surfaceinteraction_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_surfaceinteraction_export_data(self)

    def get_contactpair_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_contactpair_export_data(self)

    def get_amplitude_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_amplitude_export_data(self)

    def get_initialcondition_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_initialcondition_export_data(self)

    def get_hbc_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_hbc_export_data(self)

    def get_step_export_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_step_export_data(self)

    def create_section(self, section_type, block_id, material_id, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_section(self, section_type, block_id, material_id, options)

    def modify_section(self, section_type, section_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_section(self, section_type, section_id, options, options_marker)

    def delete_section(self, section_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_section(self, section_id)

    def create_constraint(self, constraint_type, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_constraint(self, constraint_type, options)

    def modify_constraint(self, constraint_type, constraint_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_constraint(self, constraint_type, constraint_id, options, options_marker)

    def delete_constraint(self, constraint_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_constraint(self, constraint_id)

    def create_constraint_tie_from_cubitcontactpair(self, name, position_tolerance):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_constraint_tie_from_cubitcontactpair(self, name, position_tolerance)

    def create_surfaceinteraction(self, surfacebehavior_type, options, options2):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_surfaceinteraction(self, surfacebehavior_type, options, options2)

    def modify_surfaceinteraction(self, modify_type, surfaceinteraction_id, options, options_marker, options2):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_surfaceinteraction(self, modify_type, surfaceinteraction_id, options, options_marker, options2)

    def delete_surfaceinteraction(self, surfaceinteraction_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_surfaceinteraction(self, surfaceinteraction_id)

    def create_contactpair(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_contactpair(self, options)

    def modify_contactpair(self, contactpair_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_contactpair(self, contactpair_id, options, options_marker)

    def delete_contactpair(self, contactpair_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_contactpair(self, contactpair_id)

    def create_contactpair_from_cubitcontactpair(self, surfaceinteraction_id, contactpairtype, adjust, adjust_nodeset):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_contactpair_from_cubitcontactpair(self, surfaceinteraction_id, contactpairtype, adjust, adjust_nodeset)

    def create_amplitude(self, options, options2):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_amplitude(self, options, options2)

    def modify_amplitude(self, amplitude_id, options, options_marker, options2):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_amplitude(self, amplitude_id, options, options_marker, options2)

    def delete_amplitude(self, amplitude_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_amplitude(self, amplitude_id)

    def modify_loadsforces(self, force_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_loadsforces(self, force_id, options, options_marker)

    def modify_loadspressures(self, pressure_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_loadspressures(self, pressure_id, options, options_marker)

    def modify_loadsheatfluxes(self, heatflux_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_loadsheatfluxes(self, heatflux_id, options, options_marker)

    def create_loadsgravity(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_loadsgravity(self, options)

    def modify_loadsgravity(self, gravity_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_loadsgravity(self, gravity_id, options, options_marker)

    def delete_loadsgravity(self, gravity_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_loadsgravity(self, gravity_id)

    def create_loadscentrifugal(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_loadscentrifugal(self, options)

    def modify_loadscentrifugal(self, centrifugal_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_loadscentrifugal(self, centrifugal_id, options, options_marker)

    def delete_loadscentrifugal(self, centrifugal_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_loadscentrifugal(self, centrifugal_id)

    def modify_bcsdisplacements(self, displacement_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_bcsdisplacements(self, displacement_id, options, options_marker)

    def modify_bcstemperatures(self, displacement_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_bcstemperatures(self, displacement_id, options, options_marker)

    def create_historyoutput(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_historyoutput(self, options)

    def modify_historyoutput(self, output_id, modify_type, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_historyoutput(self, output_id, modify_type, options, options_marker)

    def delete_historyoutput(self, output_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_historyoutput(self, output_id)

    def get_historyoutput_node_keys(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_historyoutput_node_keys(self)

    def get_historyoutput_element_keys(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_historyoutput_element_keys(self)

    def get_historyoutput_contact_keys(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_historyoutput_contact_keys(self)

    def create_fieldoutput(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_fieldoutput(self, options)

    def modify_fieldoutput(self, output_id, modify_type, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_fieldoutput(self, output_id, modify_type, options, options_marker)

    def delete_fieldoutput(self, output_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_fieldoutput(self, output_id)

    def get_fieldoutput_node_keys(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_fieldoutput_node_keys(self)

    def get_fieldoutput_element_keys(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_fieldoutput_element_keys(self)

    def get_fieldoutput_contact_keys(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_fieldoutput_contact_keys(self)

    def create_initialcondition(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_initialcondition(self, options)

    def modify_initialcondition(self, initialcondition_id, modify_type, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_initialcondition(self, initialcondition_id, modify_type, options, options_marker)

    def delete_initialcondition(self, initialcondition_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_initialcondition(self, initialcondition_id)

    def hbc_add_bcs(self, bcs_id, bc_type, bc_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_hbc_add_bcs(self, bcs_id, bc_type, bc_ids)

    def hbc_remove_bcs(self, bcs_id, bc_type, bc_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_hbc_remove_bcs(self, bcs_id, bc_type, bc_ids)

    def create_step(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_step(self, options)

    def modify_step(self, step_id, modify_type, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_step(self, step_id, modify_type, options, options_marker)

    def delete_step(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_step(self, step_id)

    def step_add_loads(self, step_id, load_type, load_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_add_loads(self, step_id, load_type, load_ids)

    def step_add_bcs(self, step_id, bc_type, bc_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_add_bcs(self, step_id, bc_type, bc_ids)

    def step_add_historyoutputs(self, step_id, historyoutput_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_add_historyoutputs(self, step_id, historyoutput_ids)

    def step_add_fieldoutputs(self, step_id, fieldoutput_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_add_fieldoutputs(self, step_id, fieldoutput_ids)

    def step_remove_loads(self, step_id, load_type, load_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_remove_loads(self, step_id, load_type, load_ids)

    def step_remove_bcs(self, step_id, bc_type, bc_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_remove_bcs(self, step_id, bc_type, bc_ids)

    def step_remove_historyoutputs(self, step_id, historyoutput_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_remove_historyoutputs(self, step_id, historyoutput_ids)

    def step_remove_fieldoutputs(self, step_id, fieldoutput_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_step_remove_fieldoutputs(self, step_id, fieldoutput_ids)

    def create_job(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_job(self, options)

    def modify_job(self, job_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_job(self, job_id, options, options_marker)

    def delete_job(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_job(self, job_id)

    def run_job(self, job_id, option):
        return _CalculiXCoreInterface.CalculiXCoreInterface_run_job(self, job_id, option)

    def check_jobs(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_check_jobs(self)

    def check_zombie(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_check_zombie(self)

    def wait_job(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_wait_job(self, job_id)

    def kill_job(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_kill_job(self, job_id)

    def set_job_conversion(self, job_id, conversion):
        return _CalculiXCoreInterface.CalculiXCoreInterface_set_job_conversion(self, job_id, conversion)

    def result_cgx_job(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_result_cgx_job(self, job_id)

    def result_paraview_job(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_result_paraview_job(self, job_id)

    def get_job_data(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_job_data(self, job_id)

    def get_job_console_output(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_job_console_output(self, job_id)

    def get_job_cvg(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_job_cvg(self, job_id)

    def get_job_sta(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_job_sta(self, job_id)

    def create_result(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_result(self, job_id)

    def delete_result(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_result(self, job_id)

    def load_result(self, job_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_load_result(self, job_id)

    def convert_result(self, job_id, option, block_ids, nodeset_ids, sideset_ids):
        return _CalculiXCoreInterface.CalculiXCoreInterface_convert_result(self, job_id, option, block_ids, nodeset_ids, sideset_ids)

    def project_result(self, job_id, step, totalincrement, scale):
        return _CalculiXCoreInterface.CalculiXCoreInterface_project_result(self, job_id, step, totalincrement, scale)

    def compute_von_mises_stress(self, vec):
        return _CalculiXCoreInterface.CalculiXCoreInterface_compute_von_mises_stress(self, vec)

    def compute_von_mises_strain(self, vec):
        return _CalculiXCoreInterface.CalculiXCoreInterface_compute_von_mises_strain(self, vec)

    def compute_principal_stresses(self, vec):
        return _CalculiXCoreInterface.CalculiXCoreInterface_compute_principal_stresses(self, vec)

    def compute_principal_strains(self, vec):
        return _CalculiXCoreInterface.CalculiXCoreInterface_compute_principal_strains(self, vec)

    def create_customline(self, options):
        return _CalculiXCoreInterface.CalculiXCoreInterface_create_customline(self, options)

    def modify_customline(self, customline_id, options, options_marker):
        return _CalculiXCoreInterface.CalculiXCoreInterface_modify_customline(self, customline_id, options, options_marker)

    def delete_customline(self, customline_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_delete_customline(self, customline_id)

    def get_entities(self, entity, id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_entities(self, entity, id)

    def get_customline_data(self, position, keyword, keyword_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_customline_data(self, position, keyword, keyword_id)

    def getIcon(self, name):
        return _CalculiXCoreInterface.CalculiXCoreInterface_getIcon(self, name)

    def getIcon2(self, name):
        return _CalculiXCoreInterface.CalculiXCoreInterface_getIcon2(self, name)

    def get_blocks_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_blocks_tree_data(self)

    def get_nodeset_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_nodeset_tree_data(self)

    def get_sideset_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_sideset_tree_data(self)

    def get_material_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_material_tree_data(self)

    def get_material_group_properties(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_material_group_properties(self)

    def get_sections_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_sections_tree_data(self)

    def get_constraints_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_constraints_tree_data(self)

    def get_surfaceinteractions_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_surfaceinteractions_tree_data(self)

    def get_contactpairs_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_contactpairs_tree_data(self)

    def get_amplitudes_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_amplitudes_tree_data(self)

    def get_loadsforces_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_loadsforces_tree_data(self)

    def get_loadspressures_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_loadspressures_tree_data(self)

    def get_loadsheatfluxes_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_loadsheatfluxes_tree_data(self)

    def get_loadsgravity_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_loadsgravity_tree_data(self)

    def get_loadscentrifugal_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_loadscentrifugal_tree_data(self)

    def get_bcsdisplacements_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_bcsdisplacements_tree_data(self)

    def get_bcstemperatures_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_bcstemperatures_tree_data(self)

    def get_historyoutputs_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_historyoutputs_tree_data(self)

    def get_fieldoutputs_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_fieldoutputs_tree_data(self)

    def get_initialconditions_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_initialconditions_tree_data(self)

    def get_hbcsdisplacements_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_hbcsdisplacements_tree_data(self)

    def get_hbcstemperatures_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_hbcstemperatures_tree_data(self)

    def get_steps_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_tree_data(self)

    def get_steps_loadsforces_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_loadsforces_tree_data(self, step_id)

    def get_steps_loadspressures_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_loadspressures_tree_data(self, step_id)

    def get_steps_loadsheatfluxes_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_loadsheatfluxes_tree_data(self, step_id)

    def get_steps_loadsgravity_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_loadsgravity_tree_data(self, step_id)

    def get_steps_loadscentrifugal_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_loadscentrifugal_tree_data(self, step_id)

    def get_steps_bcsdisplacements_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_bcsdisplacements_tree_data(self, step_id)

    def get_steps_bcstemperatures_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_bcstemperatures_tree_data(self, step_id)

    def get_steps_historyoutputs_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_historyoutputs_tree_data(self, step_id)

    def get_steps_fieldoutputs_tree_data(self, step_id):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_steps_fieldoutputs_tree_data(self, step_id)

    def get_customlines_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_customlines_tree_data(self)

    def get_jobs_tree_data(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_get_jobs_tree_data(self)

    def draw_all(self):
        return _CalculiXCoreInterface.CalculiXCoreInterface_draw_all(self)
    me_iface = property(_CalculiXCoreInterface.CalculiXCoreInterface_me_iface_get, _CalculiXCoreInterface.CalculiXCoreInterface_me_iface_set)

# Register CalculiXCoreInterface in _CalculiXCoreInterface:
_CalculiXCoreInterface.CalculiXCoreInterface_swigregister(CalculiXCoreInterface)



